apiVersion: apps/v1
kind: Deployment
metadata:
  name: drivex-deployment
  namespace: monitoramento-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drivex
  template:
    metadata:
      labels:
        app: drivex
    spec:
      containers:
        - name: drivex-api
          image: gcr.io/drivex-prod/drivex-api:latest
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: "mysql-service"
            - name: DB_USER
              value: "drivex"
            - name: DB_PASSWORD
              value: "drivex"
            - name: DB_NAME
              value: "drivex"

        - name: drivex-frontend
          image: gcr.io/drivex-prod/drivex-frontend:latest
          ports:
            - containerPort: 80
