apiVersion: v1
kind: Service
metadata:
  name: drivex-api-service
spec:
  type: LoadBalancer   # Expor com IP externo
  selector:
    app: drivex-api
  ports:
    - protocol: TCP
      port: 80          # Porta que será exposta publicamente
      targetPort: 3000  # Porta do container
