name: Deploy Drivex-Stage

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Buildar e fazer deploy para o Stage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS_STAGE }}'

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_STAGE }}
          export_default_credentials: true

      - name: Configure Docker for GCR
        run: |
          gcloud auth configure-docker

      - name: Build Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_STAGE }}/drivex-api:latest .

      - name: Push Docker image
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT_STAGE }}/drivex-api:latest

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: cluster-stage-drivex
          location: us-east1
          project_id: ${{ secrets.GCP_PROJECT_STAGE }}

      - name: Deploy to GKE
        run: |
          kubectl apply -f src/k8s/
