name: Deploy to Production

on:
  push:
    branches:
      - main
workflow_dispatch:

jobs:
  deploy:
    name: Build and Deploy to Production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS_PROD }}'

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_PROD }}
          export_default_credentials: true

      - name: Configure Docker for GCR
        run: gcloud auth configure-docker

      - name: Build Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_PROD }}/drivex-api:latest .

      - name: Push Docker image
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT_PROD }}/drivex-api:latest

     - name: Get GKE credentials
  run: |
    gcloud container clusters get-credentials cluster-prod-drivex --zone us-east1-b --project drivex-prod


      - name: Deploy to GKE
        run: |
          kubectl apply -f src/k8s/
